### PR TITLE
Adds the ability to host the Registration and Query API on separate IPs/ports

### PR DESCRIPTION
**Pull request by andrewbonney**

### CODE REVIEW

**Comment by garethsb-sony** [comment]
The changes to the underlying implementation look very sensible to me. I've tried it and it works for a Registry with Query API and Registration API on different ports.

I'm not sure about the UI. Both pairs of IP/Port fields are visible even when e.g. IS-04 Node API is selected in the drop-down, and I think that might confuse people. Even on the Registry APIs, the fact that they're both just labelled IP/Port means I just guessed which one was Registration API and which was Query API.

**Comment by andrewbonney** [comment]
Could you try a force reload of the page? I suspect that's a browser cache issue at play. I could always add in some cache busting for the JavaScript if necessary, but hopefully it'll stabilise over time.

**Comment by garethsb-sony** [comment]
> Could you try a force reload of the page? I suspect that's a browser cache issue at play.

Ah. Yes. Sorry. More haste, less speed, for me too!

**Comment by andrewbonney** [comment]
Good stuff. I'll merge in if that all looks ok?

**Comment by garethsb-sony** [comment]
Absolutely. Thanks, Andrew!

I wonder if we'll want to reuse this technique in the future to do tests that confirm the relationship between the Connection API and the Node API, etc.

**Comment by andrewbonney** [comment]
That's the plan :+1:

**Pull request merged**
